/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Luthfiani
 */
public class form_DataPemesanan extends javax.swing.JFrame {
private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    public String id,nm,pt,alamat,no;
    public String kd,nama,hrg;
    /**
     * Creates new form form_DataPemesanan
     */
    public form_DataPemesanan() {
        initComponents();
        datatable();
    }
    protected void aktif(){
        tid.setEnabled(true);
        tnamacos.setEnabled(true);
        tnamapt.setEnabled(true);
        talamatpt.setText("");
        tno.setText("");
        tkodebarang.setText("");
        tnamabrg.setText("");
        tharga.setText("");
        tjumlah.setText("");
        tgl.setDateFormatString("");
        tid.requestFocus();
        }
    protected void kosong(){
        tid.setText("");
        tnamacos.setText("");
        tnamapt.setText("");
        talamatpt.setText("");
        tno.setText("");
        tkodebarang.setText("");
        tnamabrg.setText("");
        tharga.setText("");
        tjumlah.setText("");
        tgl.setDateFormatString("");
    }
       
     
    protected void datatable(){
        Object[] baris ={"ID Costumer","Nama Costumer","Perusahaan","Alamat Perusahaan","No Telepon","Kode Barang","Nama Barang","Harga Barang","Jumlah Barang","Tanggal Pesan"};
        tabmode = new DefaultTableModel(null, baris);
        tabelpemesanan.setModel(tabmode);
        String sql = "select * from data_pemesanan";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("ID");
                String b = hasil.getString("Nama");
                String c = hasil.getString("Perusahaan");
                String d = hasil.getString("Alamat");
                String e = hasil.getString("NoTelp");
                String f = hasil.getString("kode_barang");
                String g = hasil.getString("nama_barang");
                String h = hasil.getString("harga_barang");
                String i = hasil.getString("jumlah_barang");
                String j = hasil.getString("tanggal");
                
                String[] data={a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
            }     
        }catch (Exception e){
        }
        }

    public void itemterpilihcostumer(){
        popup_costumer pp = new popup_costumer();
        pp.sis = this;
        tid.setText(id);
        tnamacos.setText(nm);
        tnamapt.setText(pt);
        talamatpt.setText(alamat);
        tno.setText(no);
    }
    public void itemterpilihbarang(){
        popup_barang pp = new popup_barang();
        pp.sis = this;
        tkodebarang.setText(kd);
        tnamabrg.setText(nama);
        tharga.setText(hrg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tnamacos = new javax.swing.JTextField();
        tnamapt = new javax.swing.JTextField();
        talamatpt = new javax.swing.JTextField();
        tno = new javax.swing.JTextField();
        tkodebarang = new javax.swing.JTextField();
        tnamabrg = new javax.swing.JTextField();
        tharga = new javax.swing.JTextField();
        tjumlah = new javax.swing.JTextField();
        cariCostumer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelpemesanan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tcari = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID Costumer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nama Costumer");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nama Perusahaan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Alamat Perusahaan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("No Telepon");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Kode Barang");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Nama Barang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Harga Per Batang");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Jumlah Barang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 100, 30));
        jPanel1.add(tnamacos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, -1));
        jPanel1.add(tnamapt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 160, -1));

        talamatpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talamatptActionPerformed(evt);
            }
        });
        jPanel1.add(talamatpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 160, -1));
        jPanel1.add(tno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, -1));

        tkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkodebarangActionPerformed(evt);
            }
        });
        jPanel1.add(tkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 30));
        jPanel1.add(tnamabrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, -1));
        jPanel1.add(tharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 160, -1));
        jPanel1.add(tjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 110, -1));

        cariCostumer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cari.png"))); // NOI18N
        cariCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariCostumerActionPerformed(evt);
            }
        });
        jPanel1.add(cariCostumer, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cari.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 30, 30));

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Save_1.png"))); // NOI18N
        jButton3.setText("Simpan");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, 30));

        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Edit.png"))); // NOI18N
        jButton4.setText("Ubah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 80, 30));

        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Clear.png"))); // NOI18N
        jButton5.setText("Bersih");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, 30));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Delete.png"))); // NOI18N
        jButton6.setText("Hapus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, 30));
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal Pemesanan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 350, 360));

        tabelpemesanan.setBackground(new java.awt.Color(153, 153, 153));
        tabelpemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelpemesanan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 610, 140));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 130, 470));

        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tcariKeyReleased(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 170, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cari.png"))); // NOI18N
        jButton7.setText("Cari ID");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 100, 30));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/ic home.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 70, 60));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data Pemesanan");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, -10, -1, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 820, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo_rajawali-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 110, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluar-removebg-preview.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/form pesan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 470));

        setSize(new java.awt.Dimension(1008, 506));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void talamatptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talamatptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talamatptActionPerformed

    private void tkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkodebarangActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat ("yyyy-MM-dd");
        String tanggal = sdf.format(tgl.getDate ());
        String sql = "insert into data_pemesanan values (?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setInt(1,Integer.parseInt (tid.getText()));
            stat.setString(2, tnamacos.getText());
            stat.setString(3, tnamapt.getText());
            stat.setString(4, talamatpt.getText());
            stat.setString(5, tno.getText());
            stat.setString(6, tkodebarang.getText());
            stat.setString(7, tnamabrg.getText());
            stat.setInt(8,Integer.parseInt (tharga.getText()));
            stat.setInt(9,Integer.parseInt (tjumlah.getText()));
            stat.setString(10, tanggal);
           
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            tid.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan" +e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String tampilan = "yyyy-MM-dd";
        try{
         String sql = "update data_pemesanan set Nama=?,Perusahaan=?,Alamat=?,NoTelp=?,kode_barang=?,nama_barang=?,harga_barang=?,jumlah_barang=?,tanggal=? where ID=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            
            stat.setString(1, tnamacos.getText());
            stat.setString(2, tnamapt.getText());
            stat.setString(3, talamatpt.getText());
            stat.setString(4, tno.getText());
            stat.setString(5, tkodebarang.getText());
            stat.setString(6, tnamabrg.getText());
            stat.setInt(7,Integer.parseInt (tharga.getText()));
            stat.setInt(8,Integer.parseInt (tjumlah.getText()));
            stat.setInt(9,Integer.parseInt (tid.getText()));
        
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            tid.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal diubah" +e);
        }  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cariCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariCostumerActionPerformed
        // TODO add your handling code here:
        popup_costumer pp = new popup_costumer();
        pp.sis = this;
        pp.setVisible(true);
        pp.setResizable(false);
    }//GEN-LAST:event_cariCostumerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        popup_barang pp = new popup_barang();
        pp.sis = this;
        pp.setVisible(true);
        pp.setResizable(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         kosong();
        datatable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus","konfirmasi dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from data_pemesanan where ID ='"+tid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                tid.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus" +e);
        }}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tabelpemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpemesananMouseClicked
        // TODO add your handling code here:
        int bar;
         bar = tabelpemesanan.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        
       
        tid.setText(a);
        tnamacos.setText(b);
        tnamapt.setText(c);
        talamatpt.setText(d);
        tno.setText(e);
        tkodebarang.setText(f);
        tnamabrg.setText(g);
        tharga.setText(h);
        tjumlah.setText(i);
        tgl.setDateFormatString(j);
    }//GEN-LAST:event_tabelpemesananMouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         Object[] Baris ={"ID Costumer","Nama Costumer","Perusahaan","Alamat Perusahaan","No Telepon","Kode Barang","Nama Barang","Harga Barang","Jumlah Barang"};
       tabmode = new DefaultTableModel (null, Baris);
       tabelpemesanan.setModel (tabmode);
       String sql = "select * from data_pemesanan where ID='"+tcari.getText()+"'";
       try {
           java.sql.Statement stat = conn.createStatement ();
           ResultSet hasil = stat.executeQuery(sql);
           while (hasil.next()) {
               String a = hasil.getString ("ID");
               String b = hasil.getString ("Nama");
               String c = hasil.getString ("Perusahaan");
               String d = hasil.getString ("Alamat");
               String e = hasil.getString ("NoTelp");
               String f = hasil.getString ("kode_barang");
               String g = hasil.getString ("nama_barang");
               String h = hasil.getString ("harga_barang");
               String i = hasil.getString ("jumlah_barang");
               String j = hasil.getString ("tanggal");
              
               String[] data={a,b,c,d,e,f,g,h,i,j};
               tabmode.addRow (data);
           }
           } catch (Exception e) {
       }       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         menu_utamaa mn = new menu_utamaa();
        dispose();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode () == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_tcariKeyPressed

    private void tcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyReleased
        // TODO add your handling code here:
        Object[] Baris ={"ID Costumer","Nama Costumer","Perusahaan","Alamat Perusahaan","No Telepon","Kode Barang","Nama Barang","Harga Barang","Jumlah Barang"};
       tabmode = new DefaultTableModel (null, Baris);
       tabelpemesanan.setModel (tabmode);
       String sql = "select * from data_pemesanan where ID='"+tcari.getText()+"'";
       try {
           java.sql.Statement stat = conn.createStatement ();
           ResultSet hasil = stat.executeQuery(sql);
           while (hasil.next()) {
               String a = hasil.getString ("ID");
               String b = hasil.getString ("Nama");
               String c = hasil.getString ("Perusahaan");
               String d = hasil.getString ("Alamat");
               String e = hasil.getString ("NoTelp");
               String f = hasil.getString ("kode_barang");
               String g = hasil.getString ("nama_barang");
               String h = hasil.getString ("harga_barang");
               String i = hasil.getString ("jumlah_barang");
              
               String[] data={a,b,c,d,e,f,g,h,i};
               tabmode.addRow (data);
           }
           } catch (Exception e) {
       }       
    }//GEN-LAST:event_tcariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_DataPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_DataPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_DataPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_DataPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_DataPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cariCostumer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelpemesanan;
    private javax.swing.JTextField talamatpt;
    private javax.swing.JTextField tcari;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField tkodebarang;
    private javax.swing.JTextField tnamabrg;
    private javax.swing.JTextField tnamacos;
    private javax.swing.JTextField tnamapt;
    private javax.swing.JTextField tno;
    // End of variables declaration//GEN-END:variables
}
