/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import koneksi.koneksi;

import javax.swing.JOptionPane;


/**
 *
 * @author Luthfiani
 */
public class login extends javax.swing.JFrame {
    
 private final Connection conn = new koneksi().connect();
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tuser = new javax.swing.JTextField();
        Tpswd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Bcan = new javax.swing.JButton();
        Blog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tuser.setBackground(new java.awt.Color(0, 153, 153));
        Tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuserActionPerformed(evt);
            }
        });
        getContentPane().add(Tuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 210, 30));

        Tpswd.setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().add(Tpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Silahkan Masuk");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 200, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo_rajawali-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -10, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login revisi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        Bcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcanActionPerformed(evt);
            }
        });
        getContentPane().add(Bcan, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 390, 100, 80));

        Blog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlogActionPerformed(evt);
            }
        });
        getContentPane().add(Blog, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 310, 50));

        setSize(new java.awt.Dimension(875, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlogActionPerformed
        // TODO add your handling code here:
        String user = Tuser.getText();
        String pass = Tpswd.getText();

        String sql = "select * from login where nama_pengguna='"+user+"' and kata_sandi='"+pass+"';";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                JOptionPane.showMessageDialog(null,"Login Berhasil");
                new menu_utamaa().setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null,"Login Gagal");
                Tuser.setText("");
                Tpswd.setText("");
                Tuser.requestFocus(true);
            }
        }catch (HeadlessException | SQLException e) {System.err.print(e.getMessage());}  
    }//GEN-LAST:event_BlogActionPerformed

    private void TuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuserActionPerformed

    private void BcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcanActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BcanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcan;
    private javax.swing.JButton Blog;
    private javax.swing.JPasswordField Tpswd;
    private javax.swing.JTextField Tuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
